// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Banner is the predicate function for banner builders.
type Banner func(*sql.Selector)

// Feature is the predicate function for feature builders.
type Feature func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)
